### ISSUE TITLE
Url parameters are incorrect for most async method calls

### ISSUE THREAD

**Issue by StudioWizard** [ChristianHaase/Chaase.GameSparks.NET#2]
In GameSparksAuthenticationService.cs all of the async method calls that come after DeviceAuthenticationRequest have an incorrect url parameter for the nested call to Requestor.PostString. This appears to be a simple copy paste error and should be easy to fix.

As an example, the body for RegistrationRequestAsync looks like this

            var res = await Requestor.PostStringAsync(Urls.DeviceAuthenticationRequest, SerializeRequest(requestData));
            return DeserializeResponse(res.ResponseJson);

but it should looks like this 

            var res = await Requestor.PostStringAsync(Urls.RegistrationRequest, SerializeRequest(requestData));
            return DeserializeResponse(res.ResponseJson);

There are 16 methods that are affected in this way.

Would be great if we could have a new version with this small fix

**Comment by ChristianHaase** [comment]
Hello StudioWizard.

I apologize the delay, but I've just rolled an update out to the NuGet gallery. It should be available soon. Please let me know if you experience further issues.
