### ISSUE TITLE
ScheduleBulkJobAdminRequest example?

### ISSUE THREAD

**Issue by jesusgumbau** [ChristianHaase/Chaase.GameSparks.NET#4]
Could you please provide an example on how to use the ScheduleBulkJobAdminRequest API?

**Comment by ChristianHaase** [comment]
It should be like the following:

	var adminService = new GameSparksAdminService();
	var request = new ScheduleBulkJobAdminRequest(data, moduleShortCode, playerQuery, scheduledTime, script);

	var response = adminService.ScheduleBulkJobAdminRequest(request);
